name: "Build + Run Node Action"
description: "Shared composite action to build and run any node action"
inputs:
  folder:
    required: true
    description: "Relative folder path (like actions/generate-json)"
  entry:
    required: false
    default: "index.js"
    description: "Entry JS file inside folder (default: index.js)"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies from root
      run: npm install
      shell: bash

    - name: Build with NCC
      run: |
        npx ncc build ${{ inputs.folder }}/${{ inputs.entry }} -o ${{ inputs.folder }}/dist
      shell: bash

    - name: Run built action
      run: node ${{ inputs.folder }}/dist/index.js
      shell: bash